services:
    app.controller.menu:
        class: AppBundle\Controller\MenuController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@ezpublish.query_type.registry'

    app.query_type:
        class: AppBundle\QueryType\MenuQueryType
        tags:
            - {name: ezpublish.query_type}
